bran/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from wedge import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('tarpon/', include('tarpon.urls')),
    path('wedge/', views.StockList.as_view()),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tarpon/urls.py
from django.urls import path, re_path
from . import views

app_name = 'tarpon'

urlpatterns = [
	# /music/
    path('', views.IndexView.as_view(), name='index'),

    # /music/register
    path('register/', views.UserFormView.as_view(), name='register'),

    # /music/<album_id>/
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="details"),

    # /music/album/add/
    re_path(r'album/add/$', views.AlbumCreate.as_view(), name="album-add"),
 
    # /music/album/<album_id>/
    re_path(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/<album_id>/delete/
    re_path(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # /music/<album_id>/favorite/
    #re_path(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name="favorite"),
]

tarpon/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=250)
	genre = models.CharField(max_length=100)
	album_cover = models.FileField()

	def get_absolute_url(self):
		return reverse('tarpon:details', kwargs={ 'pk' : self.pk })

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)

	#Deprecated
	#is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

wedge/models.py
from django.db import models

class Stock(models.Model):
	ticker =  models.CharField(max_length=10)
	open = models.FloatField()
	close = models.FloatField()
	volume = models.IntegerField()

	def __str__(self):
		return self.ticker

tarpon/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

tarpon/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Album
from .forms import UserForm

class IndexView(generic.ListView):
	template_name = 'tarpon/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'tarpon/details.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_cover']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_cover']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('tarpon:index')

class UserFormView(View):
	form_class = UserForm
	template_name = 'tarpon/registration_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process user registration data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			# cleaned or normalized data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			# returns User objects if credentials are correct
			user = authenticate(username=username, password=password)

			if user is not None:

				if user.is_active:
					login(request, user)
					return redirect('tarpon:index')

		return render(request, self.template_name, {'form': form})

""" Old Now-unused code
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Album

def index(request):
	all_albums = Album.objects.all()
	
	context = { 'all_albums' : all_albums }
	return render(request, 'tarpon/index.html', context)

def details(request, album_id):
	#try:
	#	album = Album.objects.get(id=album_id)
	#except Album.DoesNotExist:
	#	raise Http404("Album is Dead")
	album = get_object_or_404(Album, id=album_id)

	context = { 'album' : album }
	return render(request, 'tarpon/details.html', context)

def favorite(request, album_id):
	album = get_object_or_404(Album, id=album_id)
	try:
		selected_song = album.song_set.get(id=request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		context = {
			'album' : album,
			'error_message' : "You did not select a valid song",
		}
		return render(request, 'tarpon/details.html', context)
	else:
		selected_song.is_favorite = True
		selected_song.save()

	context = { 'album': album, }
	return render(request, 'tarpon/details.html', context)
"""

wedge/views.py
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Stock
from .serializers import StockSerializer

# Lists all stocks or creates a new one
# stocks/
class StockList(APIView):

	def get(self, request):
		stocks = Stock.objects.all()
		serializer = StockSerializer(stocks, many=True)
		return Response(serializer.data)

	def post(self):
		pass

bran/templates/tarpon/album_form.html
{% extends 'tarpon/base.html' %}
{% block title %} Add a New Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
	
	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'tarpon/form-template.html' %}
						<div class="form-group">
							<div "class=col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			
			</div>
		</div>
	</div>
</div>
{% endblock %}

bran/templates/tarpon/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}The Zone{% endblock %}</title>

	<!-- Loads the path to static files -->
	{% load static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'tarpon/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			
			<!-- Logo -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'tarpon:index' %}">The Zone</a>
			</div>

			<!-- Items -->
			<div class="collapse navbar-collapse" id="topNavBar">

				<ul class="nav navbar-nav">
					<li class="active">
						<a href ="{% url 'tarpon:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
							Albums
						</a>
					</li>
					<li class="">
						<a href ="#">
							<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
							Songs
						</a>
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="#">
					<div class="form-group">
						<input type="text" class="form-control" name="q" value="">
					</div>
					<button type="submit" class="btn btn-default">Search</button>
				</form>

				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href ="{% url 'tarpon:album-add' %}">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
							Add Album
						</a>
					</li>
					<li class="">
						<a href ="#">
							<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
							Logout
						</a>
					</li>
				</ul>
			</div>
		</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

bran/templates/tarpon/details.html
{% extends 'tarpon/base.html' %}

{% block title %}Album Details{% endblock %}

{% block body %}

	<img src="{{ album.album_cover.url }}" />

	<h1>{{ album.album_title }}</h1>
	<h3>{{ album.artist }}</h3>

	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}
	
{% endblock %}

<!-- Old code used for listing songs
<ol>
	{% for song in album.song_set.all %}
	<li>{{ song.song_title }} - {{song.file_type}} </li>
	{% endfor %}
</ol>
-->

<!-- Improper way to make a favorite form
	<form action="{% url 'tarpon:favorite' album.id %}" method="post">
		{% csrf_token %}
		{% for song in album.song_set.all %}
			<input type="radio" id="song{{ forloop.counter}}" name="song" value="{{ song.id }}">
			<label for="song{{ forloop.counter }}">
				{{ song.song_title }}
				{% if song.is_favorite %}
					<img src="http://i.imgur.com/b9b13Rd.png">
				{% endif %}
			</label><br>
		{% endfor %}
		<input type="submit" value="Favorite">
	</form>
-->

bran/templates/tarpon/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors}}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag}}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

bran/templates/tarpon/index.html
{% extends 'tarpon/base.html' %}

{% block body %}
	{% if all_albums %}
		<h3>Here are all my Albums (Look At Them! Look At Them!):</h3>
		<ul>
			{% for album in all_albums %}
				<div class="col-sm-4 col-lg-2">
					<div class="thumbnail">

					<!-- Album Cover -->
					<a href="{% url 'tarpon:details' album.id %}">
						<img src="{{ album.album_cover.url }}" class="img-responsive">
					</a>

					<div class="caption">
						<h2>{{ album.album_title }}</h2>
						<h4>{{ album.artist }}</h4>

						<!-- Details -->
						<li><a href="{% url 'tarpon:details' album.id %}">{{ album.album_title }}</a></li>

						<!-- Delete -->
						<form action="{% url 'tarpon:album-delete' album.id %}" method="post" style="display: inline;">
							{% csrf_token %}
							<input type="hidden" name="album_id" value="{{ album.id }}" />
							<button type="submit" class="btn btn-default btn-sm">
								<span class="glyphicon glyphicon-trash"></span>
							</button>
						</form>

					</div>

					</div>
				</div>
			
			<!-- Favorite
				<a href="#" class="btn btn-default btn-sm btn-favorite">
					<span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
				</a>
			-->
			{% endfor %}
		</ul>
	{% else %}
		<h3>You don't have any albums (AWWwwwww... . .)</h3>
	{% endif %}
{% endblock %}

bran/templates/tarpon/registration_form.html
{% extends 'tarpon/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}
<div class="container-fluid">
	
	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'tarpon/form-template.html' %}
						<div class="form-group">
							<div "class=col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			
			</div>
		</div>
	</div>
</div>
{% endblock %}